import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./Components/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="min-h-screen flex flex-col">
        <Navigation companyName="M. Rashid Faheem" />
        <main className="flex-grow">{children}</main>
        <footer className="bg-gray-800 text-white py-4 text-center">
          <p>&copy; 2024 My Portfolio Website. All Rights Reserved.</p>
        </footer>
        </div>
      </body>
    </html>
  );
}
